name = "review-insight"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./out"

# 为Cloudflare Pages添加配置
pages_build_output_dir = "out" 